[package]
name = "auth"
version = "0.1.0"
edition = "2021"
authors = ["Alexi Peck <alexinicolaspeck@gmail.com>"]

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }
serde_json = { version = "1.0.108" }
email_address = { version = "0.2.4", features = ["serde_support"]}
chrono = { version = "0.4.31", features = ["serde"] }
tokio = { version = "1.34.0", default-features = false, features = ["macros", "net", "rt-multi-thread", "time", "signal"] }
base64 = "0.21.5"
axum = { version = "0.7.1", features = ["http2", "tokio"] }
axum-extra = { version = "0.9.0", features = ["typed-header"] }
uuid = { version = "1.6.1", features = ["v4", "serde"] }
tower-http = { version = "0.5.0", features = ["cors", "trace"]}
blake3 = "1.5.0"
parking_lot = "0.12.1"
cookie = "0.18.0"
thiserror = "1.0.50"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.18" }
tracing = "0.1.40"
directories = "5.0.1"
regex = "1.10.2"
rust-argon2 = "2.0.0"
google-authenticator = "0.4.2"
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_core = { version = "0.6.4", features = ["getrandom"] }
openssl = { version = "0.10", features = ["vendored"] }