[package]
name = "auth"
version = "0.1.7"
edition = "2021"
authors = ["Alexi Peck <alexinicolaspeck@gmail.com>"]

[dependencies]
serde = { version = "1.0.196", features = ["derive"] }
serde_json = { version = "1.0.113" }
email_address = { version = "0.2.4", features = ["serde_support"]}
chrono = { version = "0.4.33", features = ["serde"] }
tokio = { version = "1.35.1", default-features = false, features = ["macros", "net", "rt-multi-thread", "time", "signal"] }
base64 = "0.21.7"
axum = { version = "0.7.4", features = ["http2", "tokio"] }
axum-extra = { version = "0.9.2", features = ["typed-header"] }
axum-core = "0.4.3"
tower-http = { version = "0.5.1", features = ["cors", "trace"]}
uuid = { version = "1.7.0", features = ["v4", "serde"] }#1.6.1
blake3 = "1.5.0"
parking_lot = "0.12.1"
cookie = "0.18.0"
thiserror = "1.0.56"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.18" }
tracing = "0.1.40"
directories = "5.0.1"
regex = "1.10.3"
rust-argon2 = "2.1.0"
google-authenticator = "0.4.2"
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_core = { version = "0.6.4", features = ["getrandom"] }
openssl = { version = "0.10.63", features = ["vendored"] }
lettre = "0.11.4"
diesel = { version = "2.1.4", default-features = false, features = ["sqlite", "extras", "32-column-tables", "r2d2"] }
diesel_migrations = "2.1.0"
libsqlite3-sys = { version = ">=0.17.2, <0.27.0", features = ["bundled"] }
toml = "0.8.8"
peck-lib = { git = "https://github.com/alexipeck/peck-lib" }