[package]
name = "auth"
version = "0.1.0"
edition = "2021"
authors = ["Alexi Peck <alexinicolaspeck@gmail.com>"]

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }
serde_json = { version = "1.0.108" }
email_address = { version = "0.2.4", features = ["serde_support"]}
reqwest = {version = "0.11.22", features = ["blocking", "json"]}
chrono = "0.4.31"
tokio = { version = "1.34.0", default-features = false, features = ["macros", "net", "rt-multi-thread", "time", "signal"] }
base64 = "0.21.5"
jsonwebtoken = "9.1.0"
axum = { version = "0.7.1", features = ["http2", "tokio"] }
axum-extra = { version = "0.9.0", features = ["typed-header"] }
uuid = { version = "1.6.1", features = ["v4", "serde"] }
tower-http = { version = "0.5.0", features = ["cors"]}
blake3 = "1.5.0"
parking_lot = "0.12.1"
cookie = "0.18.0"